#!/bin/zsh

# JavaScript
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Go
export PATH="$HOME/Projects/go/bin:$PATH"
export GOPATH="$HOME/Projects/go"
